events {}

http {
    server {
        listen 80;

        location /vpn/riga/ {
            proxy_pass https://212.193.20.153:4277/5a5b0820-6891-wave-89f0-1a688ab40c6c/;
        }

        location /vpn/frankfurt/ {
            proxy_pass http://5.39.252.171:8812/b1de013c-bb40-wave-9dc1-8b3e791ddbb9/;
        }
    }
}