apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: wave1/wave-work-notification-service
          imagePullPolicy: Always

          ports:
            - containerPort: 8077

          env:
            - name: JAVA_TOOL_OPTIONS
              value: >
                -XX:+UseG1GC
                -XX:MaxRAMPercentage=40
                -XX:InitialRAMPercentage=30
                -XX:MaxDirectMemorySize=96m
                -XX:MaxMetaspaceSize=96m
                -Xss256k
                -XX:+ExitOnOutOfMemoryError
                -Dio.netty.allocator.maxOrder=7
                -Dio.netty.allocator.numDirectArenas=2
                -Dio.netty.allocator.numHeapArenas=2
                -Dio.netty.maxDirectMemory=96m
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: UNLEASH_API_TOKEN
              value: "default:production.ae032b94ce75fde2580dd9b3dc5727a5b069f02328e6fe6b5474efa4"
            - name: SMTP_SERVER
              value: smtp.ya.ru
            - name: SMTP_PORT
              value: "465"
            - name: SMTP_USERNAME
              value: den200755@yandex.ru
            - name: SMTP_PASSWORD
              value: anblwqgwymmvffxq
            - name: TELEGRAM_TOKEN
              value: 8564756319:AAEB7-V723UjxBTuAcVxTEyksIHh8PlgYSg
            - name: TELEGRAM_WEB_HOOK_PATH
              value: https://wave-work.site/
            - name: TELEGRAM_WEB_HOOK_SECRET
              value: 2168b7e4-a3f7-4bdd-8250-a03bd6df5c69

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8077
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8077
            initialDelaySeconds: 40
            periodSeconds: 20