apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proposal-service-db
  namespace: infra
spec:
  selector:
    matchLabels:
      app: proposal-service-db
  serviceName: proposal-service-db
  replicas: 1
  template:
    metadata:
      labels:
        app: proposal-service-db
    spec:
      securityContext:
        fsGroup: 999
      containers:
      - name: proposal-service-db
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_DB
            value: proposal_service_db
          - name: POSTGRES_USER
            value: wave
          - name: POSTGRES_PASSWORD
            value: Den1234567890
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
