apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: app
spec:
  selector:
    app: profile-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8077
  type: ClusterIP